### ISSUE TITLE
Error parsing string with `useNativeBigInt` mode

### ISSUE THREAD

**Issue by hdoan741** [sidorares/json-bigint#88]
It seems the parser is incorrect when parsing rational number:
```
> jsbi({useNativeBigInt: true}).parse('-0.3333333333333333')
Uncaught SyntaxError: Cannot convert -0.3333333333333333 to a BigInt
```

**Comment by victorkirov** [comment]
I don't think this is an error. You can't parse a decimal into a bigint in JS. You should probably only be using `useNativeBigInt: true` if you're 100% sure that your payload won't have decimals in it.

**Comment by mois-ilya** [comment]
This issue was fixed in this PR https://github.com/sidorares/json-bigint/commit/3530541b016d9041db6c1e7019e6999790bfd857. However, the latest version on npm was released before this fix. To use the updated version, I temporarily added the package like this in my project:

```json
    "dependencies": {
        "json-bigint": "github:sidorares/json-bigint#8208aa1352eba252b60756672ab7c17f300d6ccd"
    }
```

**Comment by nathanmmiller** [comment]
@sidorares any chance a 1.0.1 could be released with the changes from the PR mentioned above by @mois-ilya ?

**Comment by sidorares** [comment]
hey @nathanmmiller I'm on vacations this week and hope to finally give issues in this repo some attention. I plan to setup release-please, once added all merged changes should be immediately published

**Comment by nathanmmiller** [comment]
Amazing, thank you @sidorares - I think I may have another weird edge case but don't want to raise an issue (or PR) until I know the updated code doesn't fix it. I look forward!

**Comment by nathanmmiller** [comment]
> hey @nathanmmiller I'm on vacations this week and hope to finally give issues in this repo some attention. I plan to setup release-please, once added all merged changes should be immediately published

Any chance this is coming soon? Thanks!

**Comment by SkylerLutz** [comment]
@sidorares can you release this please?

**Comment by SkylerLutz** [comment]
@sidorares can you please release this?

**Comment by flbn** [comment]
can we please make a new release? lib has been stale on npm for years now :|

**Comment by nathanmmiller** [comment]
I think this is abandonware at this point. Is anyone using alternatives and if so, what?

If not, @sidorares would you prefer someone else take over this library?

**Comment by scastrec** [comment]
Hi,
Will a new version be published ?
Thanks

**Comment by Ivan-Korolenko** [comment]
@nathanmmiller 
Regarding alternatives, you might want to try my library that does the same thing and doesn't have this issue. As a bonus, it also supports round-trip operations, works with TypeScript, and you can just replace every `JSON.stringify()` and `JSON.parse()` call in your project with its functions (`JSONStringify()` and `JSONParse()` respectively), among other features:
https://www.npmjs.com/package/json-with-bigint

**Comment by nathanmmiller** [comment]
> [@nathanmmiller](https://github.com/nathanmmiller) Regarding alternatives, you might want to try my library that does the same thing and doesn't have this issue. As a bonus, it also supports round-trip operations, works with TypeScript, and you can just replace every `JSON.stringify()` and `JSON.parse()` call in your project with its functions (`JSONStringify()` and `JSONParse()` respectively), among other features: https://www.npmjs.com/package/json-with-bigint

Thank you, I'll check it out!

**Comment by nathanmmiller** [comment]
For anyone who comes upon this issue, @Ivan-Korolenko's library is an excellent replacement, I am now using it instead of this.
